/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package assignment4;


import java.awt.Color;
import java.awt.Font;
import java.awt.event.KeyEvent;
import javax.swing.JButton;
import javax.swing.JColorChooser;

/**
 *
 * @author Alan Stewart, K00223375
 */
public class TypingTutor extends javax.swing.JFrame {

    private JButton[] keyJButtons = new JButton[ KeyEvent.KEY_LAST  + 1 ];
    
    private String[] fontNames = new String[6]; 
    
    Color buttonColor = Color.YELLOW;
    Color textColor = Color.BLACK;
   
    
    
    /**
     * Creates new form TypingTutor
     */
    public TypingTutor() {
        
    fontNames[0]= "Arial Black";
    fontNames[1]= "Helvetica";
    fontNames[2]= "Cooper Black";
    fontNames[3]= "Rockwell";
    fontNames[4]= "Times New Roman";
    fontNames[5]= "Comic Sans MS";
    
        
        
        initComponents();
               
        keyJButtons[KeyEvent.VK_Q]=qButton;
        keyJButtons[KeyEvent.VK_W]=wButton;
        keyJButtons[KeyEvent.VK_E]=eButton;
        keyJButtons[KeyEvent.VK_R]=rButton;
        keyJButtons[KeyEvent.VK_T]=tButton;
        keyJButtons[KeyEvent.VK_Y]=yButton;
        keyJButtons[KeyEvent.VK_U]=uButton;
        keyJButtons[KeyEvent.VK_I]=iButton;
        keyJButtons[KeyEvent.VK_O]=oButton;
        keyJButtons[KeyEvent.VK_P]=pButton;
        keyJButtons[KeyEvent.VK_A]=aButton;
        keyJButtons[KeyEvent.VK_S]=sButton;
        keyJButtons[KeyEvent.VK_D]=dButton;
        keyJButtons[KeyEvent.VK_F]=fButton;
        keyJButtons[KeyEvent.VK_G]=gButton;
        keyJButtons[KeyEvent.VK_H]=hButton;
        keyJButtons[KeyEvent.VK_J]=jButton;
        keyJButtons[KeyEvent.VK_K]=kButton;
        keyJButtons[KeyEvent.VK_L]=LButton;
        keyJButtons[KeyEvent.VK_Z]=zButton;
        keyJButtons[KeyEvent.VK_X]=xButton;
        keyJButtons[KeyEvent.VK_C]=cButton;
        keyJButtons[KeyEvent.VK_V]=vButton;
        keyJButtons[KeyEvent.VK_B]=bButton;
        keyJButtons[KeyEvent.VK_N]=nButton;
        keyJButtons[KeyEvent.VK_M]=mButton;
        keyJButtons[KeyEvent.VK_1]=num1Button;
        keyJButtons[KeyEvent.VK_2]=num2Button;
        keyJButtons[KeyEvent.VK_3]=num3Button;
        keyJButtons[KeyEvent.VK_4]=num4Button;
        keyJButtons[KeyEvent.VK_5]=num5Button;
        keyJButtons[KeyEvent.VK_6]=num6Button;
        keyJButtons[KeyEvent.VK_7]=num7Button;
        keyJButtons[KeyEvent.VK_8]=num8Button;
        keyJButtons[KeyEvent.VK_9]=num9Button;
        keyJButtons[KeyEvent.VK_0]=num0Button;
        keyJButtons[KeyEvent.VK_SPACE]=spaceButton;
        keyJButtons[KeyEvent.VK_COMMA]=commaButton;
        keyJButtons[KeyEvent.VK_MINUS]=minusButton;
        keyJButtons[KeyEvent.VK_EQUALS]=plusButton;
        keyJButtons[KeyEvent.VK_BACK_SPACE]=bsButton;
        keyJButtons[KeyEvent.VK_TAB]=tabButton;
        keyJButtons[KeyEvent.VK_OPEN_BRACKET]=lbButton;
        keyJButtons[KeyEvent.VK_CLOSE_BRACKET]=rbButton;
        keyJButtons[KeyEvent.VK_BACK_SLASH]=bslashButton;
        keyJButtons[KeyEvent.VK_SHIFT]=shiftButton;
        keyJButtons[KeyEvent.VK_PERIOD]=periodButton;
        keyJButtons[KeyEvent.KEY_LOCATION_UNKNOWN]=tilButton;
        keyJButtons[KeyEvent.VK_ENTER]=enterButton;
        keyJButtons[KeyEvent.VK_QUOTE]=quotButton;
        keyJButtons[KeyEvent.VK_UP]=upButton;
        keyJButtons[KeyEvent.VK_LEFT]=leftButton;
        keyJButtons[KeyEvent.VK_DOWN]=downButton;
        keyJButtons[KeyEvent.VK_RIGHT]=rightButton;
        keyJButtons[KeyEvent.VK_CAPS_LOCK]=capsButton;
        keyJButtons[KeyEvent.VK_SEMICOLON]=colButton;
        keyJButtons[KeyEvent.VK_SLASH]=qMarkButton; 
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        buttonGroup2 = new javax.swing.ButtonGroup();
        jScrollPane1 = new javax.swing.JScrollPane();
        jta = new javax.swing.JTextPane();
        qButton = new javax.swing.JButton();
        wButton = new javax.swing.JButton();
        eButton = new javax.swing.JButton();
        rButton = new javax.swing.JButton();
        tButton = new javax.swing.JButton();
        pButton = new javax.swing.JButton();
        oButton = new javax.swing.JButton();
        iButton = new javax.swing.JButton();
        uButton = new javax.swing.JButton();
        yButton = new javax.swing.JButton();
        aButton = new javax.swing.JButton();
        sButton = new javax.swing.JButton();
        dButton = new javax.swing.JButton();
        fButton = new javax.swing.JButton();
        gButton = new javax.swing.JButton();
        hButton = new javax.swing.JButton();
        jButton = new javax.swing.JButton();
        kButton = new javax.swing.JButton();
        LButton = new javax.swing.JButton();
        zButton = new javax.swing.JButton();
        xButton = new javax.swing.JButton();
        cButton = new javax.swing.JButton();
        vButton = new javax.swing.JButton();
        bButton = new javax.swing.JButton();
        nButton = new javax.swing.JButton();
        mButton = new javax.swing.JButton();
        commaButton = new javax.swing.JButton();
        lbButton = new javax.swing.JButton();
        rbButton = new javax.swing.JButton();
        tilButton = new javax.swing.JButton();
        num1Button = new javax.swing.JButton();
        num2Button = new javax.swing.JButton();
        num3Button = new javax.swing.JButton();
        num4Button = new javax.swing.JButton();
        num5Button = new javax.swing.JButton();
        num6Button = new javax.swing.JButton();
        num7Button = new javax.swing.JButton();
        num8Button = new javax.swing.JButton();
        num9Button = new javax.swing.JButton();
        num0Button = new javax.swing.JButton();
        minusButton = new javax.swing.JButton();
        tabButton = new javax.swing.JButton();
        bsButton = new javax.swing.JButton();
        plusButton = new javax.swing.JButton();
        bslashButton = new javax.swing.JButton();
        capsButton = new javax.swing.JButton();
        shiftButton = new javax.swing.JButton();
        colButton = new javax.swing.JButton();
        quotButton = new javax.swing.JButton();
        enterButton = new javax.swing.JButton();
        periodButton = new javax.swing.JButton();
        qMarkButton = new javax.swing.JButton();
        spaceButton = new javax.swing.JButton();
        upButton = new javax.swing.JButton();
        downButton = new javax.swing.JButton();
        rightButton = new javax.swing.JButton();
        leftButton = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        displayMenu = new javax.swing.JMenu();
        clearText = new javax.swing.JMenuItem();
        jSeparator1 = new javax.swing.JPopupMenu.Separator();
        textColour = new javax.swing.JMenuItem();
        ButtonColour = new javax.swing.JMenuItem();
        formatMenu = new javax.swing.JMenu();
        sytleMenu = new javax.swing.JMenu();
        boldMenuItem = new javax.swing.JCheckBoxMenuItem();
        italicMenuItem = new javax.swing.JCheckBoxMenuItem();
        sizeMenu = new javax.swing.JMenu();
        sizeFont12 = new javax.swing.JRadioButtonMenuItem();
        sizeFont16 = new javax.swing.JRadioButtonMenuItem();
        sizeFont20 = new javax.swing.JRadioButtonMenuItem();
        typeMenu = new javax.swing.JMenu();
        jRadioButtonMenuItem1 = new javax.swing.JRadioButtonMenuItem();
        jRadioButtonMenuItem2 = new javax.swing.JRadioButtonMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jta.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jtaKeyPressed(evt);
            }
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jtaKeyReleased(evt);
            }
        });
        jScrollPane1.setViewportView(jta);

        qButton.setText("Q");
        qButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                qButtonActionPerformed(evt);
            }
        });

        wButton.setText("W");

        eButton.setText("E");

        rButton.setText("R");

        tButton.setText("T");

        pButton.setText("P");

        oButton.setText("O");

        iButton.setText("I");

        uButton.setText("U");

        yButton.setText("Y");

        aButton.setText("A");

        sButton.setText("S");

        dButton.setText("D");

        fButton.setText("F");

        gButton.setText("G");

        hButton.setText("H");

        jButton.setText("J");

        kButton.setText("K");

        LButton.setText("L");

        zButton.setText("Z");

        xButton.setText("X");

        cButton.setText("C");

        vButton.setText("V");

        bButton.setText("B");

        nButton.setText("N");

        mButton.setText("M");

        commaButton.setText(",");

        lbButton.setText("[");

        rbButton.setText("]");

        tilButton.setText("~");
        tilButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tilButtonActionPerformed(evt);
            }
        });

        num1Button.setText("1");
        num1Button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                num1ButtonActionPerformed(evt);
            }
        });

        num2Button.setText("2");

        num3Button.setText("3");

        num4Button.setText("4");

        num5Button.setText("5");

        num6Button.setText("6");

        num7Button.setText("7");

        num8Button.setText("8");

        num9Button.setText("9");

        num0Button.setText("0");

        minusButton.setText("-");
        minusButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                minusButtonActionPerformed(evt);
            }
        });

        tabButton.setText("Tab");

        bsButton.setText("BackSpace");
        bsButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bsButtonActionPerformed(evt);
            }
        });

        plusButton.setText("+");
        plusButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                plusButtonActionPerformed(evt);
            }
        });

        bslashButton.setText("\\");

            capsButton.setText("Caps");
            capsButton.addActionListener(new java.awt.event.ActionListener() {
                public void actionPerformed(java.awt.event.ActionEvent evt) {
                    capsButtonActionPerformed(evt);
                }
            });

            shiftButton.setText("Shift");

            colButton.setText(";");
            colButton.addActionListener(new java.awt.event.ActionListener() {
                public void actionPerformed(java.awt.event.ActionEvent evt) {
                    colButtonActionPerformed(evt);
                }
            });

            quotButton.setText("\"");

            enterButton.setText("Enter");

            periodButton.setText(".");

            qMarkButton.setText("?");

            upButton.setText("^");

            downButton.setText("v");

            rightButton.setText(">");

            leftButton.setText("<");

            jLabel1.setText("Type some text using your keyboard. The keys you press will be highlighted and text will be displayed. ");

            jLabel2.setText("Note: Clicking the buttons wiht your mouse will not perform any action.");

            displayMenu.setText("Display");

            clearText.setText("Clear Text");
            displayMenu.add(clearText);
            displayMenu.add(jSeparator1);

            textColour.setText("Text Colour");
            textColour.addActionListener(new java.awt.event.ActionListener() {
                public void actionPerformed(java.awt.event.ActionEvent evt) {
                    textColourActionPerformed(evt);
                }
            });
            displayMenu.add(textColour);

            ButtonColour.setText("Button Colour");
            ButtonColour.addActionListener(new java.awt.event.ActionListener() {
                public void actionPerformed(java.awt.event.ActionEvent evt) {
                    ButtonColourActionPerformed(evt);
                }
            });
            displayMenu.add(ButtonColour);

            jMenuBar1.add(displayMenu);

            formatMenu.setText("Format");

            sytleMenu.setText("Style");

            boldMenuItem.setText("Bold");
            boldMenuItem.addActionListener(new java.awt.event.ActionListener() {
                public void actionPerformed(java.awt.event.ActionEvent evt) {
                    boldMenuItemActionPerformed(evt);
                }
            });
            sytleMenu.add(boldMenuItem);

            italicMenuItem.setText("Italic");
            italicMenuItem.addActionListener(new java.awt.event.ActionListener() {
                public void actionPerformed(java.awt.event.ActionEvent evt) {
                    italicMenuItemActionPerformed(evt);
                }
            });
            sytleMenu.add(italicMenuItem);

            formatMenu.add(sytleMenu);

            sizeMenu.setText("Size");
            buttonGroup1.add(sizeMenu);

            buttonGroup1.add(sizeFont12);
            sizeFont12.setSelected(true);
            sizeFont12.setText("12");
            sizeFont12.addActionListener(new java.awt.event.ActionListener() {
                public void actionPerformed(java.awt.event.ActionEvent evt) {
                    sizeFont12ActionPerformed(evt);
                }
            });
            sizeMenu.add(sizeFont12);

            buttonGroup1.add(sizeFont16);
            sizeFont16.setText("16");
            sizeMenu.add(sizeFont16);

            sizeFont20.setText("20");
            sizeMenu.add(sizeFont20);

            formatMenu.add(sizeMenu);

            typeMenu.setText("Type");
            buttonGroup2.add(typeMenu);

            buttonGroup2.add(jRadioButtonMenuItem1);
            jRadioButtonMenuItem1.setSelected(true);
            jRadioButtonMenuItem1.setText("Aerial Black");
            jRadioButtonMenuItem1.addActionListener(new java.awt.event.ActionListener() {
                public void actionPerformed(java.awt.event.ActionEvent evt) {
                    jRadioButtonMenuItem1ActionPerformed(evt);
                }
            });
            typeMenu.add(jRadioButtonMenuItem1);

            buttonGroup2.add(jRadioButtonMenuItem2);
            jRadioButtonMenuItem2.setText("Cooper Black");
            typeMenu.add(jRadioButtonMenuItem2);

            formatMenu.add(typeMenu);

            jMenuBar1.add(formatMenu);

            setJMenuBar(jMenuBar1);

            javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
            getContentPane().setLayout(layout);
            layout.setHorizontalGroup(
                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addContainerGap()
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jScrollPane1)
                        .addGroup(layout.createSequentialGroup()
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(tilButton)
                                    .addGap(0, 0, 0)
                                    .addComponent(num1Button)
                                    .addGap(0, 0, 0)
                                    .addComponent(num2Button)
                                    .addGap(0, 0, 0)
                                    .addComponent(num3Button)
                                    .addGap(0, 0, 0)
                                    .addComponent(num4Button)
                                    .addGap(0, 0, 0)
                                    .addComponent(num5Button)
                                    .addGap(0, 0, 0)
                                    .addComponent(num6Button)
                                    .addGap(0, 0, 0)
                                    .addComponent(num7Button)
                                    .addGap(0, 0, 0)
                                    .addComponent(num8Button)
                                    .addGap(0, 0, 0)
                                    .addComponent(num9Button)
                                    .addGap(0, 0, 0)
                                    .addComponent(num0Button)
                                    .addGap(0, 0, 0)
                                    .addComponent(minusButton)
                                    .addGap(0, 0, 0)
                                    .addComponent(plusButton)
                                    .addGap(0, 0, 0)
                                    .addComponent(bsButton))
                                .addGroup(layout.createSequentialGroup()
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                        .addGroup(layout.createSequentialGroup()
                                            .addComponent(tabButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                            .addGap(0, 0, 0)
                                            .addComponent(qButton)
                                            .addGap(0, 0, 0)
                                            .addComponent(wButton)
                                            .addGap(0, 0, 0)
                                            .addComponent(eButton)
                                            .addGap(0, 0, 0)
                                            .addComponent(rButton)
                                            .addGap(0, 0, 0)
                                            .addComponent(tButton)
                                            .addGap(0, 0, 0)
                                            .addComponent(yButton)
                                            .addGap(0, 0, 0)
                                            .addComponent(uButton)
                                            .addGap(0, 0, 0)
                                            .addComponent(iButton)
                                            .addGap(0, 0, 0)
                                            .addComponent(oButton)
                                            .addGap(0, 0, 0)
                                            .addComponent(pButton)
                                            .addGap(0, 0, 0)
                                            .addComponent(lbButton)
                                            .addGap(0, 0, 0)
                                            .addComponent(rbButton)
                                            .addGap(0, 0, 0)
                                            .addComponent(bslashButton))
                                        .addGroup(layout.createSequentialGroup()
                                            .addComponent(shiftButton, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addGap(0, 0, 0)
                                            .addComponent(zButton)
                                            .addGap(0, 0, 0)
                                            .addComponent(xButton)
                                            .addGap(0, 0, 0)
                                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                                .addGroup(layout.createSequentialGroup()
                                                    .addComponent(cButton)
                                                    .addGap(0, 0, 0)
                                                    .addComponent(vButton)
                                                    .addGap(0, 0, 0)
                                                    .addComponent(bButton)
                                                    .addGap(0, 0, 0)
                                                    .addComponent(nButton)
                                                    .addGap(0, 0, 0)
                                                    .addComponent(mButton)
                                                    .addGap(0, 0, 0)
                                                    .addComponent(commaButton))
                                                .addComponent(spaceButton, javax.swing.GroupLayout.PREFERRED_SIZE, 244, javax.swing.GroupLayout.PREFERRED_SIZE))
                                            .addComponent(periodButton)
                                            .addGap(0, 0, 0)
                                            .addComponent(qMarkButton)
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                                .addComponent(upButton)
                                                .addGroup(layout.createSequentialGroup()
                                                    .addComponent(leftButton)
                                                    .addGap(0, 0, 0)
                                                    .addComponent(downButton))))
                                        .addGroup(layout.createSequentialGroup()
                                            .addComponent(capsButton, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addGap(0, 0, 0)
                                            .addComponent(aButton)
                                            .addGap(0, 0, 0)
                                            .addComponent(sButton)
                                            .addGap(0, 0, 0)
                                            .addComponent(dButton)
                                            .addGap(0, 0, 0)
                                            .addComponent(fButton)
                                            .addGap(0, 0, 0)
                                            .addComponent(gButton)
                                            .addGap(0, 0, 0)
                                            .addComponent(hButton)
                                            .addGap(0, 0, 0)
                                            .addComponent(jButton)
                                            .addGap(0, 0, 0)
                                            .addComponent(kButton)
                                            .addGap(0, 0, 0)
                                            .addComponent(LButton)
                                            .addGap(0, 0, 0)
                                            .addComponent(colButton)
                                            .addGap(0, 0, 0)
                                            .addComponent(quotButton)
                                            .addGap(0, 0, 0)
                                            .addComponent(enterButton)))
                                    .addGap(0, 0, 0)
                                    .addComponent(rightButton))
                                .addComponent(jLabel1)
                                .addComponent(jLabel2))
                            .addGap(0, 0, Short.MAX_VALUE)))
                    .addContainerGap())
            );
            layout.setVerticalGroup(
                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(5, 5, 5)
                    .addComponent(jLabel1)
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                    .addComponent(jLabel2)
                    .addGap(20, 20, 20)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(tilButton)
                        .addComponent(num1Button)
                        .addComponent(num2Button)
                        .addComponent(num3Button)
                        .addComponent(num4Button)
                        .addComponent(num5Button)
                        .addComponent(num6Button)
                        .addComponent(num7Button)
                        .addComponent(num8Button)
                        .addComponent(num9Button)
                        .addComponent(num0Button)
                        .addComponent(minusButton)
                        .addComponent(plusButton)
                        .addComponent(bsButton))
                    .addGap(0, 0, 0)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(qButton)
                        .addComponent(wButton)
                        .addComponent(eButton)
                        .addComponent(rButton)
                        .addComponent(tButton)
                        .addComponent(yButton)
                        .addComponent(uButton)
                        .addComponent(iButton)
                        .addComponent(oButton)
                        .addComponent(pButton)
                        .addComponent(lbButton)
                        .addComponent(rbButton)
                        .addComponent(tabButton)
                        .addComponent(bslashButton))
                    .addGap(0, 0, 0)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(aButton)
                        .addComponent(sButton)
                        .addComponent(dButton)
                        .addComponent(fButton)
                        .addComponent(gButton)
                        .addComponent(hButton)
                        .addComponent(jButton)
                        .addComponent(kButton)
                        .addComponent(LButton)
                        .addComponent(capsButton)
                        .addComponent(colButton)
                        .addComponent(quotButton)
                        .addComponent(enterButton))
                    .addGap(0, 0, 0)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                            .addComponent(upButton)
                            .addGap(0, 0, 0)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(downButton)
                                .addComponent(rightButton)
                                .addComponent(leftButton)))
                        .addGroup(layout.createSequentialGroup()
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(zButton)
                                .addComponent(xButton)
                                .addComponent(cButton)
                                .addComponent(vButton)
                                .addComponent(bButton)
                                .addComponent(nButton)
                                .addComponent(mButton)
                                .addComponent(commaButton)
                                .addComponent(shiftButton)
                                .addComponent(periodButton)
                                .addComponent(qMarkButton))
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(spaceButton, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGap(64, 64, 64))
            );

            pack();
        }// </editor-fold>//GEN-END:initComponents

    private void jtaKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jtaKeyPressed
        keyJButtons[evt.getKeyCode()].setBackground(buttonColor);
    }//GEN-LAST:event_jtaKeyPressed

    private void jtaKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jtaKeyReleased
        keyJButtons[evt.getKeyCode()].setBackground(Color.lightGray);
    }//GEN-LAST:event_jtaKeyReleased

    private void boldMenuItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_boldMenuItemActionPerformed
        
        Font font = new Font("Times New Roman", Font.BOLD,16);
        jta.setFont(font);
    }//GEN-LAST:event_boldMenuItemActionPerformed

    private void italicMenuItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_italicMenuItemActionPerformed
        Font font = new Font("Times New Roman", Font.ITALIC,16);
        jta.setFont(font);
    }//GEN-LAST:event_italicMenuItemActionPerformed

    private void tilButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tilButtonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tilButtonActionPerformed

    private void num1ButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_num1ButtonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_num1ButtonActionPerformed

    private void minusButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_minusButtonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_minusButtonActionPerformed

    private void bsButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bsButtonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_bsButtonActionPerformed

    private void plusButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_plusButtonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_plusButtonActionPerformed

    private void qButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_qButtonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_qButtonActionPerformed

    private void colButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_colButtonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_colButtonActionPerformed

    private void capsButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_capsButtonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_capsButtonActionPerformed

    private void textColourActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_textColourActionPerformed
        
       textColor = JColorChooser.showDialog(this, "Select A Text Colour", textColor);
        
        jta.setForeground(textColor);
        
    }//GEN-LAST:event_textColourActionPerformed

    private void ButtonColourActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ButtonColourActionPerformed
        
        buttonColor = JColorChooser.showDialog(this, "Select A Button Colour", buttonColor);
        
    }//GEN-LAST:event_ButtonColourActionPerformed

    private void sizeFont12ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sizeFont12ActionPerformed
        
        
        
    }//GEN-LAST:event_sizeFont12ActionPerformed

    private void jRadioButtonMenuItem1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButtonMenuItem1ActionPerformed
        Font font = new Font(fontNames[0],Font.PLAIN,12);
        jta.setFont(font);
    }//GEN-LAST:event_jRadioButtonMenuItem1ActionPerformed

    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TypingTutor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TypingTutor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TypingTutor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TypingTutor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TypingTutor().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuItem ButtonColour;
    private javax.swing.JButton LButton;
    private javax.swing.JButton aButton;
    private javax.swing.JButton bButton;
    private javax.swing.JCheckBoxMenuItem boldMenuItem;
    private javax.swing.JButton bsButton;
    private javax.swing.JButton bslashButton;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.ButtonGroup buttonGroup2;
    private javax.swing.JButton cButton;
    private javax.swing.JButton capsButton;
    private javax.swing.JMenuItem clearText;
    private javax.swing.JButton colButton;
    private javax.swing.JButton commaButton;
    private javax.swing.JButton dButton;
    private javax.swing.JMenu displayMenu;
    private javax.swing.JButton downButton;
    private javax.swing.JButton eButton;
    private javax.swing.JButton enterButton;
    private javax.swing.JButton fButton;
    private javax.swing.JMenu formatMenu;
    private javax.swing.JButton gButton;
    private javax.swing.JButton hButton;
    private javax.swing.JButton iButton;
    private javax.swing.JCheckBoxMenuItem italicMenuItem;
    private javax.swing.JButton jButton;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JRadioButtonMenuItem jRadioButtonMenuItem1;
    private javax.swing.JRadioButtonMenuItem jRadioButtonMenuItem2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JPopupMenu.Separator jSeparator1;
    private javax.swing.JTextPane jta;
    private javax.swing.JButton kButton;
    private javax.swing.JButton lbButton;
    private javax.swing.JButton leftButton;
    private javax.swing.JButton mButton;
    private javax.swing.JButton minusButton;
    private javax.swing.JButton nButton;
    private javax.swing.JButton num0Button;
    private javax.swing.JButton num1Button;
    private javax.swing.JButton num2Button;
    private javax.swing.JButton num3Button;
    private javax.swing.JButton num4Button;
    private javax.swing.JButton num5Button;
    private javax.swing.JButton num6Button;
    private javax.swing.JButton num7Button;
    private javax.swing.JButton num8Button;
    private javax.swing.JButton num9Button;
    private javax.swing.JButton oButton;
    private javax.swing.JButton pButton;
    private javax.swing.JButton periodButton;
    private javax.swing.JButton plusButton;
    private javax.swing.JButton qButton;
    private javax.swing.JButton qMarkButton;
    private javax.swing.JButton quotButton;
    private javax.swing.JButton rButton;
    private javax.swing.JButton rbButton;
    private javax.swing.JButton rightButton;
    private javax.swing.JButton sButton;
    private javax.swing.JButton shiftButton;
    private javax.swing.JRadioButtonMenuItem sizeFont12;
    private javax.swing.JRadioButtonMenuItem sizeFont16;
    private javax.swing.JRadioButtonMenuItem sizeFont20;
    private javax.swing.JMenu sizeMenu;
    private javax.swing.JButton spaceButton;
    private javax.swing.JMenu sytleMenu;
    private javax.swing.JButton tButton;
    private javax.swing.JButton tabButton;
    private javax.swing.JMenuItem textColour;
    private javax.swing.JButton tilButton;
    private javax.swing.JMenu typeMenu;
    private javax.swing.JButton uButton;
    private javax.swing.JButton upButton;
    private javax.swing.JButton vButton;
    private javax.swing.JButton wButton;
    private javax.swing.JButton xButton;
    private javax.swing.JButton yButton;
    private javax.swing.JButton zButton;
    // End of variables declaration//GEN-END:variables
}
